---
title: "Homework 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[Home Page](index.html)

1. Transform an excel style data frame turn into a what you need for a .csv file. 

```
Find: \s{2,}
Replace: ,
```
I used the /s to remove any spaces and then the {2} to remove any spaces that we greater than 2. I then replaced the spaces with a comma.

2. To reformat a list of names and institutions so commas are removed from the names and institutions are in parenthesis. 

```
Find:(\w+),\s(\w+),\s(.*)
Replace:\1 \2 (\3)
```

I used the first (`\w`+) to capture the first part of the name and put it in parenthesis so it was something that I wanted to keep.  I then put the ,`\s` which captured the comma and the space which I wanted to remove.  Followed by the next (`\w`+) to capture the next word and repeated the same ,`\s` to remove the next comma and space. Lastly I put (.*) to capture the final word.  In the replace I added back in the spaces and added the parenthesis so I had the final output that I wanted.

3. To create new lines between each of the names of songs. 

```
Find:(.mp3)\s
Replace:\1\n
```

I selected each of the .mp3 file names as items that I wanted to keep and also selected the spaces.  In the replace I kept the mp3 file names and replaced the space with an enter and this put each of the song names on new lines. 

4. Want to grab the 4 digit code and move it to the end of the song title. 

```
Find:(\d{4})(.+)(.mp3)
Replace:\2_\1\3
```

I first selected the 4 digits at the start of the title, then I selected all of the words using the .+ and finally I selected the .mp3.  I kept everything in parenthesis because I didn't want to remove anything in the transformation.  Then during the replace step, I reordered the components and added an underscore. 

5. This was to take the data frame and shorten the title so it is abbreviated with just the first letter and remove one of the numeric values.

```
Find:(^\w)\w+,(\w+),\d*\.\d+,(\d+)
Replace:\1_\2,\3
```

I first used the (^w) to let it know that I wanted to keep the first character value then put the rest of the word outside of the parenthesis so it would cut off the rest and just leave the first letter.  I removed the first comma and in the replace I added in an _. Then I kept the second word all the following comma but removed the first numeric value along with its associated decimal point.  I also kept the final digit. 

6. This was another version of abbreviating the dataset with both just the fist initial, a shortened species name and only one of the numeric values. 

```
Find:(^\w)\w+,(\w{4})\w+,\d*\.\d+,(\d+)
Replace:\1_\2,\3
```

I kept some of the code similar to previous question.  I kept the first letter using (^`\w`) and then moved the rest of the letter and the comma outside of the parenthesis using `\w`+,then I only wanted to keep the first 4 letters of the next word so I used (`\w`{4}) and then removed the rest of the word using `\w`+.  The rest of the code with removing the numeric values as the same as the previous question. 

7. To rearrange the dataset so the species and genus names are fused with the first 3 letters of each followed by the two columns of numerical data in reversed order.

```
Find:(^\w{3})\w+,(\w{3})\w+,(\d*\.\d+),(\d+)
Replace:\1\2, \4, \3
```

I captured the first 3 letters of the first word and wanted to keep it so I put it in parenthesis (^`\w`{3}) I then removed the rest of that word and the comma `\w`+,.  Next I did a similar operation with the second word (`\w`{3})`\w`+, and just added the comma back in during the replace step.  I then wanted to keep the digits so I marked to keep them but wanted to remove the comma between them for formatting so that was left outside of the parenthesis.  Then during the replace step I re-ordered the numbers so they would show up in the right order during the transformation and added a comma back in between them.  