---
title: "Lab#6"
author: "Rachel Swanwick"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[Home Page](index.html)

# Homework #6
# February 23, 2022
# RHS

```{r}
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
```
```{r}
# adding in own data 
z <- read.csv("Freeman_data.csv",header=TRUE,sep=",")
str(z)
summary(z)

# make one of the columns its own variables 
q <- z$Photo
```

```{r}
# this is plotting the code as a histogram 
p1 <- ggplot(data=z, aes(x=Cond, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1)
```
```{r}
# We are now modifying the data to add a kernel density plot of the data.  This is a variation on the histogram that uses kernal smoothing to plot values that will allow for a smoother distribution by smoothing out the noise.  
p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
```
```{r}
# Next fit a normal distribution to your data and grab the maximum likelihood estimators of the two parameters of the normal, the mean and the variance. This helps you predict the probability of an occurance within a certain interval. 
normPars <- fitdistr(z$Cond,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```
```{r}
# Now we call the dnorm function inside ggplot’s stat_function to generate the probability density for the normal distribution. Then we pass those parameters (meanML and sdML to stat_function). 
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$Cond),len=length(z$Cond))

 stat <- stat_function(aes(x =  xval, y = ..y..), fun = dnorm, colour="red", n = length(z$Cond), args = list(mean = meanML, sd = sdML))
 p1 + stat
```
```{r}
# Add in the curve for the exponential
expoPars <- fitdistr(z$Cond,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$Cond), args = list(rate=rateML))
p1 + stat + stat2
```
```{r}
# Plot uniform probability density
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$Cond), args = list(min=min(z$Cond), max=max(z$Cond)))
 p1 + stat + stat2 + stat3
```
```{r}
# Plot gamma probability density
gammaPars <- fitdistr(z$Cond,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$Cond), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4
```
```{r}
# Plot beta probability density
pSpecial <- ggplot(data=z, aes(x=Cond/(max(Cond + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$Cond/max(z$Cond + 0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$Cond), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial
```
```{r}
#3 
# The gamma distribution curve is best fitted for this dataset because it most closely aligns with the kernal density plot of the actual data 
```
```{r}
#4 
x <- rgamma(n= 500, shapeML, rateML) 
x <- data.frame(1:500,x)
head(x)

#plot histogram 
p1 <- ggplot(data=x, aes(x=x, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1)

# plot probability density curve
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(x$x),len=length(x$x))

 stat <- stat_function(aes(x =  xval, y = ..y..), fun = dnorm, colour="red", n = length(z$Cond), args = list(mean = meanML, sd = sdML))
 p1 + stat
 
# generate a fresh histogram plot of the original data 
p1 <- ggplot(data=z, aes(x=Cond, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1) 

# include a probability density curve 
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$Cond),len=length(z$Cond))

 stat <- stat_function(aes(x =  xval, y = ..y..), fun = dnorm, colour="red", n = length(z$Cond), args = list(mean = meanML, sd = sdML))
 p1 + stat

# How do the two histogram profiles compare? Do you think the model is doing a good job of simulating realistic data that match your original measurements? Why or why not?

# It is doing an ok job of comparing between the simulated dataset and the original dataset.  The density on the original dataset and simulated dataset are both around 3.5 so that is similar.  The bends are a little different between the two curves and the simulated dataset has a wider curve than the original dataset and the original dataset also has a steeper curve than the stimulated dataset. 
```